language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

matrix:
  include:
  - jdk: oraclejdk8
    script: mvn -q install -Parquillian-tomee-managed
  - jdk: oraclejdk8
    script: mvn -q install -Pwildfly-swarm
  - jdk: oraclejdk8
    script: mvn -q install -Phammock
